const state={all:[],filtered:[],program:[],programFilter:'all',page:1,pageSize:15,charts:{}};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const nf=new Intl.NumberFormat('pt-BR',{maximumFractionDigits:1});
const df=new Intl.DateTimeFormat('pt-BR',{timeZone:'UTC'});
const sum=(a,k)=>a.reduce((t,x)=>t+(Number(x[k])||0),0);
const group=(rows,key)=>rows.reduce((m,r)=>{(m[r[key]||'Não informado']??=[]).push(r);return m},{});
const weekNumber=s=>Number(String(s).replace(/\D/g,''))||0;
const shortName=n=>{const p=String(n).trim().split(/\s+/);return p.length>2?`${p[0]} ${p.at(-1)}`:n};
Chart.defaults.font.family='Inter, sans-serif';Chart.defaults.color='#718294';Chart.defaults.borderColor='#e6edf2';

Promise.all([fetch('data/production.json').then(r=>r.json()),fetch('data/programacao.json').then(r=>r.json())]).then(([production,program])=>{
  state.all=production.records.filter(r=>r.nome&&r.semana);state.program=program.atividades;init();applyFilters();renderProgram();
}).catch(error=>{console.error(error);document.body.insertAdjacentHTML('beforeend','<div class="load-error">Não foi possível carregar os dados. Publique a pasta completa no GitHub Pages.</div>')});

function init(){
  const weeks=[...new Set(state.all.map(r=>r.semana))].sort((a,b)=>weekNumber(a)-weekNumber(b));
  const leaders=[...new Set(state.all.map(r=>r.nome))].sort((a,b)=>a.localeCompare(b,'pt-BR'));
  $('#weekFilter').insertAdjacentHTML('beforeend',weeks.map(v=>`<option>${v}</option>`).join(''));
  $('#leaderFilter').insertAdjacentHTML('beforeend',leaders.map(v=>`<option>${v}</option>`).join(''));
  const dates=state.all.map(r=>r.data).filter(Boolean).sort();if(dates.length){['dateStart','dateEnd'].forEach(id=>{$('#'+id).min=dates[0];$('#'+id).max=dates.at(-1)});$('#lastDate').textContent=df.format(new Date(dates.at(-1)+'T00:00:00Z'))}
  ['weekFilter','leaderFilter','shiftFilter','dateStart','dateEnd'].forEach(id=>$('#'+id).addEventListener('change',()=>{state.page=1;applyFilters()}));
  $('#clearFilters').addEventListener('click',()=>{['weekFilter','leaderFilter','shiftFilter'].forEach(id=>$('#'+id).value='all');$('#dateStart').value='';$('#dateEnd').value='';$('#searchInput').value='';state.page=1;applyFilters()});
  $('#searchInput').addEventListener('input',()=>{state.page=1;renderTable()});
  $('#prevPage').addEventListener('click',()=>{if(state.page>1){state.page--;renderTable()}});$('#nextPage').addEventListener('click',()=>{const p=Math.ceil(searchedRows().length/state.pageSize);if(state.page<p){state.page++;renderTable()}});$('#downloadCsv').addEventListener('click',downloadCsv);
  $$('.program-filters button').forEach(btn=>btn.addEventListener('click',()=>{$$('.program-filters button').forEach(x=>x.classList.remove('active'));btn.classList.add('active');state.programFilter=btn.dataset.discipline;renderProgram()}));
}

function applyFilters(){const w=$('#weekFilter').value,l=$('#leaderFilter').value,s=$('#shiftFilter').value,start=$('#dateStart').value,end=$('#dateEnd').value;state.filtered=state.all.filter(r=>(w==='all'||r.semana===w)&&(l==='all'||r.nome===l)&&(s==='all'||r.turno===s)&&(!start||r.data>=start)&&(!end||r.data<=end));renderKpis();renderCharts();renderRanking();renderTable()}
function activeRows(){const modern=state.filtered.filter(r=>r.simulado);return modern.length?modern:state.filtered}
function dailyAverage(rows,key){const d=Object.values(group(rows,'data')).map(x=>sum(x,key));return d.length?sum(d.map(v=>({v})),'v')/d.length:0}

function renderKpis(){const r=state.filtered,a=activeRows(),total=sum(r,'total'),present=sum(a,'presente'),planned=sum(a,'efetivoPlanejado'),absence=sum(a,'faltas'),productivity=present?sum(a,'total')/present:0,night=a.filter(x=>x.turno==='Noturno');$('#kpiTotal').textContent=nf.format(total);$('#kpiProductivity').textContent=nf.format(productivity);$('#kpiPlanned').textContent=nf.format(dailyAverage(a,'efetivoPlanejado'));$('#kpiPresent').textContent=nf.format(dailyAverage(a,'presente'));$('#kpiAbsence').textContent=planned?`${nf.format(absence/planned*100)}%`:'—';$('#absenceDetail').textContent=`${nf.format(absence)} faltas acumuladas • ref. 17%`;$('#kpiNight').textContent=nf.format(dailyAverage(night,'presente'));$('#gaugeValue').textContent=nf.format(productivity);const degrees=Math.min(360,productivity/60*360);$('#gaugeFill').style.background=`conic-gradient(${productivity>=42?'#12b886':'#f6a11a'} ${degrees}deg,#e8eef2 ${degrees}deg)`;$('#gaugeStatus').textContent=productivity>=42?'META ATINGIDA':'ABAIXO DA META';$('#gaugeStatus').className=`status-pill ${productivity>=42?'':'warning'}`}

function chart(id,config){if(state.charts[id])state.charts[id].destroy();state.charts[id]=new Chart($(id),config)}
function baseOptions(){return{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{backgroundColor:'#06182b',padding:10,cornerRadius:8}},scales:{x:{grid:{display:false},ticks:{font:{size:9}}},y:{beginAtZero:true,ticks:{font:{size:9},callback:v=>nf.format(v)}}}}}
function renderCharts(){const r=state.filtered,weekly=group(r,'semana'),weeks=Object.keys(weekly).sort((a,b)=>weekNumber(a)-weekNumber(b));chart('#weeklyChart',{type:'bar',data:{labels:weeks,datasets:[{label:'Montagem',data:weeks.map(k=>sum(weekly[k],'montagem')),backgroundColor:'#0ea5d8',borderRadius:4,maxBarThickness:32},{label:'Desmontagem',data:weeks.map(k=>sum(weekly[k],'desmontagem')),backgroundColor:'#f6a11a',borderRadius:4,maxBarThickness:32}]},options:baseOptions()});
  const shifts=group(r,'turno'),day=sum(shifts.Diurno||[],'total'),night=sum(shifts.Noturno||[],'total'),legacy=sum(shifts['Não informado']||[],'total'),shiftData=legacy?[day,night,legacy]:[day,night],shiftLabels=legacy?['Diurno','Noturno','Base histórica']:['Diurno','Noturno'];$('#shiftTotal').textContent=nf.format(sum(r,'total'));chart('#shiftChart',{type:'doughnut',data:{labels:shiftLabels,datasets:[{data:shiftData,backgroundColor:['#0ea5d8','#7559d9','#9aa8b5'],borderWidth:0}]},options:{responsive:true,maintainAspectRatio:false,cutout:'72%',plugins:{legend:{position:'bottom',labels:{boxWidth:8,usePointStyle:true,padding:17,font:{size:9}}}}}});
  const a=activeRows(),daily=group(a,'data'),dates=Object.keys(daily).sort(),prod=dates.map(d=>{const p=sum(daily[d],'presente');return p?sum(daily[d],'total')/p:0});chart('#productivityChart',{type:'line',data:{labels:dates.map(d=>d.slice(5).split('-').reverse().join('/')),datasets:[{label:'Produtividade',data:prod,borderColor:'#12b886',backgroundColor:'rgba(18,184,134,.1)',fill:true,tension:.35,pointRadius:2},{label:'Meta',data:dates.map(()=>42),borderColor:'#e25555',borderDash:[5,5],pointRadius:0}]},options:{...baseOptions(),plugins:{legend:{display:true,position:'bottom',labels:{boxWidth:8,usePointStyle:true,font:{size:9}}}},scales:{x:{grid:{display:false},ticks:{maxTicksLimit:8,font:{size:8}}},y:{beginAtZero:false,suggestedMin:25,suggestedMax:55,ticks:{font:{size:9}}}}}});
  const modern=activeRows(),days=group(modern,'data'),dayLabels=Object.keys(days).sort();chart('#effectiveChart',{type:'bar',data:{labels:dayLabels.map(d=>d.slice(5).split('-').reverse().join('/')),datasets:[{label:'Planejado',data:dayLabels.map(d=>sum(days[d],'efetivoPlanejado')),backgroundColor:'#b8c7d3',borderRadius:3},{label:'Presente',data:dayLabels.map(d=>sum(days[d],'presente')),backgroundColor:'#0ea5d8',borderRadius:3},{label:'Faltas',data:dayLabels.map(d=>sum(days[d],'faltas')),backgroundColor:'#e25555',borderRadius:3}]},options:{...baseOptions(),plugins:{legend:{display:true,position:'bottom',labels:{boxWidth:8,usePointStyle:true,font:{size:9}}}},scales:{x:{stacked:false,grid:{display:false},ticks:{maxTicksLimit:12,font:{size:8}}},y:{beginAtZero:true,ticks:{font:{size:9}}}}}});
  const leaders=Object.entries(group(modern,'nome')).map(([name,rows])=>{const p=sum(rows,'presente');return{name,prod:p?sum(rows,'total')/p:0}}).sort((a,b)=>b.prod-a.prod).slice(0,12);chart('#leadersChart',{type:'bar',data:{labels:leaders.map(x=>shortName(x.name)),datasets:[{label:'Produtividade',data:leaders.map(x=>x.prod),backgroundColor:leaders.map(x=>x.prod>=42?'#12b886':'#f6a11a'),borderRadius:4},{label:'Meta',type:'line',data:leaders.map(()=>42),borderColor:'#e25555',borderDash:[5,5],pointRadius:0}]},options:{...baseOptions(),indexAxis:'y',plugins:{legend:{display:true,position:'bottom',labels:{boxWidth:8,usePointStyle:true,font:{size:9}}}},scales:{x:{beginAtZero:true,suggestedMax:60,ticks:{font:{size:9}}},y:{grid:{display:false},ticks:{font:{size:8}}}}}})}

function renderRanking(){const list=Object.entries(group(state.filtered,'nome')).map(([name,rows])=>({name,total:sum(rows,'total')})).sort((a,b)=>b.total-a.total).slice(0,10),max=list[0]?.total||1;$('#rankingList').innerHTML=list.length?list.map((x,i)=>`<div class="rank-row"><span class="rank-pos">${String(i+1).padStart(2,'0')}</span><span class="rank-name" title="${x.name}">${shortName(x.name)}</span><span class="rank-bar"><i style="width:${x.total/max*100}%"></i></span><span class="rank-value">${nf.format(x.total)} ML</span></div>`).join(''):'<p>Sem dados para os filtros selecionados.</p>'}
function renderProgram(){const rows=state.programFilter==='all'?state.program:state.program.filter(x=>x.disciplina===state.programFilter),avg=rows.length?sum(rows.map(x=>({v:x.conclusao})),'v')/rows.length:0;$('#programCount').textContent=`${rows.length} atividades`;$('#programAverage').textContent=`${nf.format(avg)}% médio`;$('#programList').innerHTML=rows.map(x=>`<article class="program-row"><span class="program-id">${x.id}</span><div class="program-main"><strong title="${x.atividade}">${x.atividade}</strong><small>${x.disciplina} • ${x.local} • ${x.turno}</small></div><span class="program-leader" title="${x.encarregado}">${x.encarregado}</span><div class="program-progress"><span class="progress-track"><i style="width:${x.conclusao}%"></i></span><b>${x.conclusao}%</b></div></article>`).join('')}
function searchedRows(){const q=$('#searchInput').value.trim().toLocaleLowerCase('pt-BR');return !q?state.filtered:state.filtered.filter(r=>r.nome.toLocaleLowerCase('pt-BR').includes(q)||String(r.idEnesa).includes(q))}
function renderTable(){const rows=searchedRows().sort((a,b)=>b.data.localeCompare(a.data)||weekNumber(b.semana)-weekNumber(a.semana)),pages=Math.max(1,Math.ceil(rows.length/state.pageSize));state.page=Math.min(state.page,pages);const start=(state.page-1)*state.pageSize;$('#dataBody').innerHTML=rows.slice(start,start+state.pageSize).map(r=>`<tr><td>${r.semana}${r.simulado?'*':''}</td><td>${r.data?df.format(new Date(r.data+'T00:00:00Z')):'—'}</td><td>${r.turno||'—'}</td><td>${r.nome}</td><td>${r.efetivoPlanejado??'—'}</td><td>${nf.format(r.presente)}</td><td>${r.faltas??'—'}</td><td>${nf.format(r.hhTotal)}</td><td>${nf.format(r.montagem)}</td><td>${nf.format(r.desmontagem)}</td><td><b>${nf.format(r.total)}</b></td><td>${r.produtividade!=null?nf.format(r.produtividade):'—'}</td><td>${r.simulado?`<span class="chip ${r.classificacao==='Produtivo'?'good':'bad'}">${r.classificacao}</span>`:'<span class="chip legacy">Histórico</span>'}</td></tr>`).join('');$('#recordCount').textContent=`${nf.format(rows.length)} registros • * simulado`;$('#pageInfo').textContent=`Página ${state.page} de ${pages}`;$('#prevPage').disabled=state.page<=1;$('#nextPage').disabled=state.page>=pages}
function downloadCsv(){const keys=['semana','data','turno','idEnesa','nome','efetivoPlanejado','presente','faltas','hhTotal','montagem','desmontagem','total','produtividade','classificacao','simulado'],head=['Semana','Data','Turno','ID ENESA','Encarregado','Efetivo Previsto','Presentes','Faltas','HH Total','Montagem','Desmontagem','Total','ML/MOD/dia','Classificação','Simulado'];const esc=v=>`"${String(v??'').replaceAll('"','""')}"`,csv='\ufeff'+[head,...searchedRows().map(r=>keys.map(k=>r[k]))].map(row=>row.map(esc).join(';')).join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download='controle-producao-filtrado.csv';a.click();URL.revokeObjectURL(a.href)}
